name: Publish packages in production

on:
  workflow_dispatch:
    inputs:
      version:
        description: bump version
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.23.6

      - name: Set up Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build libs
        run: |
          rm -rf ./packages/asktug-theme/dist
          pnpm run build:ui
          pnpm run build:site-components

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
