name: Reusable publish

on:
  workflow_call:
    inputs:
      bump-version:
        required: true
        type: string
      package:
        required: true
        type: string
    secrets:
      PUBLISH_TOKEN:
        description: 'Token for publishing npm package'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.build-env }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}

      - name: Set up Node.js 18.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.14.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: actions/download-artifact@v3
        name: Download ${{ inputs.package }} artifact
        with:
          name: ${{ inputs.package }}

      - name: Un-compress target
        run: tar -zxf ${{ inputs.package }}.tar && rm ${{ inputs.package }}.tar

      - name: Setup GIT
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Bump version
        id: bump-version
        run: |
          BUMPED_VERSION=$(npm version ${{ inputs.bump-version }})
          echo bump ${{ inputs.package }} to ${BUMPED_VERSION}
          echo "::set-output name=version::${BUMPED_VERSION}"
        working-directory: packages/${{ inputs.package }}

      - name: Publish
        run: |
          npm config set //npm.pkg.github.com/:_authToken '${{ secrets.PUBLISH_TOKEN }}'
          npm publish
        working-directory: packages/${{ inputs.package }}

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "packages/${{ inputs.package }}/package.json"
          message: "release(${{ inputs.package }}): ${{ steps.bump-version.outputs.version }}"
          commit: '--no-verify --signoff'
          tag: ${{ inputs.package }}/${{ steps.bump-version.outputs.version }}
          pull: '--rebase --autostash'
          push: true
          committer_name: GitHub Actions
          committer_email: actions@github.com
