name: Reusable deploy

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      build-env:
        required: true
        type: string
    secrets:
      OSS_ACCESS_KEY:
        required: true
      OSS_ACCESS_SECRET:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.build-env }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.12.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 6.23.6
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: actions/download-artifact@v3
        name: Download ${{ inputs.build-env }} artifact
        with:
          name: ${{ inputs.package }}-${{ inputs.build-env }}

      - name: Un-compress target
        run: tar -zxf ${{ inputs.package }}-${{ inputs.build-env }}.tar && rm ${{ inputs.package }}-${{ inputs.build-env }}.tar

      - name: Deploy ${{ inputs.package }}-${{ inputs.build-env }} to Ali OSS
        uses: Menci/upload-to-oss@beta-v3
        with:
          access-key-id: ${{ secrets.OSS_ACCESS_KEY }}
          access-key-secret: ${{ secrets.OSS_ACCESS_SECRET }}
          bucket: tidb-community-site
          endpoint: oss-accelerate.aliyuncs.com
          local-path: packages/${{ inputs.package }}/dist
          remote-path: tidb-community-ui
          headers: '{ "Cache-Control": "no-cache" }'
          no-delete-remote-files: true
