name: Reusable publish

on:
  workflow_call:
    inputs:
      bump-version:
        required: true
        type: string
      package:
        required: true
        type: string
    secrets:
      PUBLISH_TOKEN:
        description: 'Token for publishing npm package'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.build-env }}

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}

      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.23.6

      - name: Set up Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Resolve prod dependencies
        id: prod-dep-caches
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json', 'packages/*/package-lock.json') }}
          restore-keys: ${{ runner.os }}-build

      - uses: actions/download-artifact@v2
        name: Download ${{ inputs.package }} artifact
        with:
          name: ${{ inputs.package }}

      - name: Un-compress target
        run: tar -zxf ${{ inputs.package }}.tar && rm ${{ inputs.package }}.tar

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "release(${{ inputs.project }}): ${{ steps.bump-version.outputs.version }}"
          commit_options: '--no-verify --signoff'
          tagging_message: ${{ steps.bump-version.outputs.version }}
          file_pattern: "packages/${{ inputs.project }}/package.json"

      - name: Setup GIT
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Bump version
        id: bump-version
        run: |
          BUMPED_VERSION=$(npm version ${{ inputs.bump-version }})
          echo bump ${{ inputs.package }} to ${BUMPED_VERSION}
          echo "::set-output name=version::${BUMPED_VERSION}"
        working-directory: packages/${{ inputs.package }}

      - name: Publish
        run: |
          npm config set //npm.pkg.github.com/:_authToken '${{ secrets.PUBLISH_TOKEN }}'
          npm publish
        working-directory: packages/${{ inputs.package }}
