name: UI Scripts production

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.23.6

      - name: Set up Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build libs
        run: |
          rm -rf ./packages/ui-scripts/dist
          pnpm run build:ui
          pnpm run build:site-components

      - name: Build production
        run: pnpm run build:ui-scripts:production
        env:
          BUILD_REF: production@${{ github.event.ref }}

      - name: Upload to Aliyun oss
        id: upload_to_oss
        uses: AliyunWorkbench/workbench-oss@1.0.0
        with:
          ACCESS_KEY: ${{ secrets.OSS_ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.OSS_ACCESS_SECRET }}
          OSS_REGION: oss-cn-beijing
          OSS_BUCKET: tidb-community-site
          OSS_PATH: /tidb-community-ui/
          UPLOAD_PATH: /tidb-community-ui/packages/ui-scripts/dist
